# numpy応用演習

以下のような3次元配列に変換せよ

In [3]:
import numpy as np
e = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
f = e.reshape(2,3,2)
print(f)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


1. 上記3次元配列から2つ目の行列中の9を取り出せ
2. 同様に1つ目の行列中の2 3を取り出せ
   

In [ ]:
print(f[1,1,1])
print(f[0,1])

# 連結
1. 1次元配列 gを、2次元配列（行列）eの最下行に追加せよ
2. 1次元配列 hを、eの左に１列追加せよ  
ヒント：np.concatenateを使う

In [ ]:
import numpy as np
e=np.arange(12).reshape(3,4)
g=np.array([1,2,3,4])
h=np.array([1,2,3])
i = np.concatenate([e,g.reshape(1,-1)],axis=0)
j = np.concatenate([e,h.reshape(-1,1)],axis=1)
print(i)
print(j)

# インデックスの取得
1. 上記の2次元配列 e について行毎に最大値を取り出せ
2. 同様にして行毎に最大値のインデックス（列番号）を取り出せ
3. e について列毎に最大値を取り出せ
4. 同様にして列毎に最大値のインデックス（行番号）を取り出せ
5. e について3の倍数だけを取り出せ
6. e について3の倍数のインデックスを取り出せ


In [ ]:
print(np.max(e,1))
print(np.argmax(e,1))
print(np.max(e,0))
print(np.argmax(e,0))
print(e[e%3==0])
print(np.where(e%3==0))

# 行列の積
1. ベクトル g と行列 eの積を計算せよ（1行3列となる）
2. 行列 e とベクトル h.Tの積を計算せよ(転置は.T)
3. g・e・h.T を計算せよ

In [2]:
import numpy as np
e=np.arange(12).reshape(4,3)
print(e)
g=np.array([1,2,3,4])
h=np.array([1,2,3])

print(np.dot(g,e))
print(np.dot(e,h.reshape(-1,1)))
print(np.dot(np.dot(g,e),h.reshape(-1,1)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[60 70 80]
[[ 8]
 [26]
 [44]
 [62]]
[440]


以下のxとW.Tの積を数式で表すことを考える。数式でベクトルを表現する場合は常に縦ベクトルである。 したがって、xは数式で表すと$x^T$である。  
また、行列$A$,$B$の転置は、転置の公式より、$(AB)^T=B^TA^T$のように変換できる。つまり、以下のxとW.Tの積は、公式の右辺に相当する。  
そこで、公式の左辺の形式でxとW.Tの積を計算して、結果が同一になることを確認せよ。  
この計算は、ニューラルネットワークの何に該当するか？　ノードとエッジを用いて、このコーディングを絵に書いてみよ

In [ ]:
import numpy as np
x=np.array([1,2,3])
W = np.arange(12).reshape(4,3)
print(np.dot(x,W.T))

In [ ]:
print(np.dot(W,x.T).T)